name: update README.md

on:
  schedule:
    - cron: '*/30 * * * *'
  push:
    branches: 
      - main
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      
      - name: Setup node.js
        uses: actions/setup-node@v1
        with: 
          node-version: 12.18.1
      - run: npm install
      - run: npm run build --if-present
      
      - name: Update README.md
        run: node update-profile.js
        
      - name: Commit and push
        run: |-
          git diff
          git config --global user.name "readme-auto-updater"
          git add -A
          git commit -m "Updated README.md." || exit 0
          git push
